# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c7bf6f22174597562c64560af5fa9e1e5db3d7efae7d6759aa007aad0337e1c86f8217578e8f923820832f811061b09904e5574175a2b08f8b77d4440c92819

test:
  secret_key_base: 5c4ad59922f428d37e8ee4db838a517381fd63f1a6dc45c7c93e2fa5ddba9c79cff300b82894c3434033b35c27e825d9af605f1b3663f75c29c1523aae4035ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || SecureRandom.hex(64) %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || SecureRandom.hex(64) %>
